[install]
git = {}
cmake = {}
pkg-config = {}
pcre = {}
libgcrypt = {}
libevent = {}
openssl = {}
jemalloc = {}
icu58 = {}
gnumake = {}
gcc-wrapper = {}
cxx = {}
coreutils = {}
inetutils = {}
vim = {}
zlib = {}
bison = {}
strace = {}

[vars]

[hook]
script= """
	if [ ! -d build ]; then
		mkdir -p build

		# fix me, should use cmake variables
		cp -f local_options ./driver/src/

		export ICQ_DIR="$FLOX_ENV"
		export ICU_ROOT="$FLOX_ENV"
		export OPENSSL_ROOT_DIR="$FLOX_ENV"
		export ZLIB_ROOT="$FLOX_ENV"
		export PCRE_ROOT="$FLOX_ENV"
		echo "$ICU_DIR"
		pushd build
		cmake ../driver -DPACKAGE_UIDS=OFF -DPACKAGE_DB=OFF

		make install
		popd
	fi
	./run.sh
"""
